[WIP] format GCK standard package structure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,30 +1,104 @@
 #!/bin/sh
+#   gck.configure - Prepares the build system for GCK distributions
+#   FEATURES:
+#       - Generate config.mak
+#       - Sets C Flags
+#
+#    COMPILATION (Linux - POSIX):
+#        ./make
+#
+#
+#   LICENSE: BSD-3-Clause
+#
+#   Copyright (c) 2025 GCK
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+# 
+# 1. Redistributions of source code must retain the above copyright notice, this
+#    list of conditions and the following disclaimer.
+# 
+# 2. Redistributions in binary form must reproduce the above copyright notice,
+#    this list of conditions and the following disclaimer in the documentation
+#    and/or other materials provided with the distribution.
+# 
+# 3. Neither the name of the copyright holder nor the names of its
+#    contributors may be used to endorse or promote products derived from
+#    this software without specific prior written permission.
+# 
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
+# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
+# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
+# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
+# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+#
 
-usage() {
-cat <<EOF
-Usage: $0 [OPTION]... [VAR=VALUE]...
+me=$0
+scriptversion="1.0.0"
 
-To assign environment variables (e.g., CC, CFLAGS...), specify them as
-VAR=VALUE.
+version="make $scriptversion
 
-CC              C compiler command [detected]
-CFLAGS          C compiler flags [-g, ...]
-LDFLAGS         C linker flags
+Copyright (C) 2025 GCK.
 
---prefix=<path> Set the install path
---debug         Flags for debug build, overrides CFLAGS
+This is free software; you are free to change and redistribute it.
+There is NO WARRANTY, to the extent permitted by law."
 
-EOF
-exit 0
-}
+usage="\
+Usage: $me [OPTION]...
+Prepares the build system for GCK distribtuions
+
+Options:
+	
+   --release
+   --debug
+   --prefix PREFIX
+
+   --help     print this help and exit
+   --version  output version information
+
+Environment variables:
+
+   CC      C compiler command
+   CFLAGS  C compiler flags
+
+Use these variables to override the choices made by 'configure'."
+
+release=false
+debug=false
+prefix=/usr/local
+CFLAGS=
+CC=
+
+while test $# -gt 0; do
+  case $1 in
+    --help) echo "$usage"; exit 0;;
+    --version) echo "$version"; exit 0;;
+    --release) release=true;;
+    --debug) debug=true;;
+    --prefix) shift; prefix=${1:?};;
+    CC=*) CC=${arg#*=} ;;
+    CFLAGS=*) CFLAGS=${arg#*=} ;;
+    -*)
+     echo "$0: Unknown option '$1'." >&2
+     echo "$0: Try '--help' for more information.'$1'." >&2
+     exit 1;;
+  esac
+  shift
+done
+
+if [ "$release" = true ] && [ "$debug" = true ]; then
+	echo "$0: Can't set both '--release' and '--debug'." >&2
+	echo "$0: Try '--help' for more information.'$1'." >&2
+	exit 1
+fi
 
 cmdexists() { type "$1" >/dev/null 2>&1 ; }
 trycc() { [ -z "$CC" ] && cmdexists "$1" && CC=$1 ; }
-
-prefix=/usr/local
-CFLAGS="-std=c23"
-LDFLAGS=
-CC=
 
 printf "checking for C compiler... "
 trycc gcc
@@ -33,18 +107,6 @@ trycc cc
 trycc icx
 printf "%s\n" "$CC"
 
-DEBUG=false
-for arg; do
-case "$arg" in
---help|-h) usage ;;
---prefix=*) prefix=${arg#*=} ;;
---debug) DEBUG=true ;;
-CFLAGS=*) CFLAGS=${arg#*=} ;;
-LDFLAGS=*) LDFLAGS=${arg#*=} ;;
-CC=*) CC=${arg#*=} ;;
-*) printf "Unrecognized option %s\n" "$arg" ;;
-esac
-done
 
 printf "checking whether C compiler works... "
 tmpc="$(mktemp -d)/test.c"
@@ -56,35 +118,12 @@ printf "no; %s\n" "$output"
 exit 1
 fi
 
-GDEBUGCFLAGS="-std=c23 -O0 -g3 -Wall -Wextra -Wpedantic -Werror -Wshadow -Wdouble-promotion -Wformat=2 -Wnull-dereference -Wconversion -Wsign-conversion -Wcast-qual -Wcast-align=strict -Wpointer-arith -Wstrict-overflow=5 -Wstrict-aliasing=2 -Wundef -Wunreachable-code -Wswitch-enum -fanalyzer -fsanitize=undefined,address -fstack-protector-strong -D_FORTIFY_SOURCE=3"
-CDEBUGCFLAGS="-std=gnu2x -O0 -g3 -Wall -Wextra -Wpedantic -Werror -Wshadow -Wdouble-promotion -Wformat=2 -Wnull-dereference -Wconversion -Wsign-conversion -Wcast-qual -Wcast-align=strict -Wpointer-arith -Wstrict-overflow=5 -Wstrict-aliasing=2 -Wundef -Wunreachable-code -Wswitch-enum -fanalyzer -fsanitize=undefined,address -fstack-protector-strong -D_FORTIFY_SOURCE=3"
-
-if [ -z "$DEBUG" ]; then
-case "$CC" in
-gcc) CFLAGS="$GDEBUGFLAGS";;
-clang) CFLAGS="$CDEBUGFLAGS";;
-*) ;;
-esac
-else
-case "$CC" in
-gcc) ;;
-clang) ;;
-*) ;;
-esac
-fi
-
-case "$OSTYPE" in
-cygwin|msys) 
-echo "enabling windows specific flags"
-CFLAGS="-v $CFLAGS"
-;;
-esac
-
 printf "creating config.mak... "
 {
 printf "PREFIX=%s\n" "$prefix"
 printf "CFLAGS=%s\n" "$CFLAGS"
-printf "LDFLAGS=%s\n" "$LDFLAGS"
 printf "CC=%s\n" "$CC"
 } > config.mak
 printf "done\n"
+
+# End: configure
