[WIP] format GCK standard package structure

diff --git a/tools/Cleanup b/tools/Cleanup
--- a/tools/Cleanup
+++ b/tools/Cleanup
@@ -1,5 +1,75 @@
 #!/bin/sh
-# Usage: ./Cleanup
+#   gck.Cleanup - Cleanup the distribution
+#
+#   FEATURES:
+#       - Run makefile cleans
+#       - Run formats
+#       - Cleanup artifacts
+#
+#    COMPILATION (Linux - POSIX):
+#        ./Cleanup
+#
+#
+#   LICENSE: BSD-3-Clause
+#
+#   Copyright (c) 2025 GCK
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+# 
+# 1. Redistributions of source code must retain the above copyright notice, this
+#    list of conditions and the following disclaimer.
+# 
+# 2. Redistributions in binary form must reproduce the above copyright notice,
+#    this list of conditions and the following disclaimer in the documentation
+#    and/or other materials provided with the distribution.
+# 
+# 3. Neither the name of the copyright holder nor the names of its
+#    contributors may be used to endorse or promote products derived from
+#    this software without specific prior written permission.
+# 
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
+# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
+# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
+# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
+# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
+# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+#
+
+me=$0
+scriptversion="1.0.0"
+
+version="make $scriptversion
+
+Copyright (C) 2025 GCK.
+
+This is free software; you are free to change and redistribute it.
+There is NO WARRANTY, to the extent permitted by law."
+
+usage="\
+Usage: $me [OPTION]...
+Standard GCK cleanup
+
+Options:
+
+   --help     print this help and exit
+   --version  output version information"
+
+while test $# -gt 0; do
+  case $1 in
+    --help) echo "$usage"; exit 0;;
+    --version) echo "$version"; exit 0;;
+    -*)
+     echo "$0: Unknown option '$1'." >&2
+     echo "$0: Try '--help' for more information.'$1'." >&2
+     exit 1;;
+  esac
+  shift
+done
 
 fatal() {
     echo "fatal: $*" >&2
@@ -10,12 +80,13 @@ run() {
     "$@" || fatal "could not run: $*"
 }
 
-[ ! -d "./src" ] && fatal "must be run from parent directory"
+[ -d "./git" ] && fatal "must be run from parent directory"
 
 run sh ./tools/format
 run rm -rf .cache
 run rm -f compile_commands.json
 run make distclean
-run make -C doc clean
 
 echo "done."
+
+# End: Cleanup
